name: build cache

on:
  workflow_dispatch:
  schedule:
    - cron: "*/20 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: adopt
        cache: sbt
    - name: Run tests
      run: sbt scalafmtSbtCheck scalafmtCheck test:scalafmtCheck test
    - name: Scala 3
      run: sbt '++ 3.1.2!' update # TODO
    - name: Build executable
      run: sbt executable